#include QMK_KEYBOARD_H

enum xd75_keycodes {
  KC_QWERTY = SAFE_RANGE,
  KC_COLEMAK
};

#define KC_CTESC   LCTL_T(KC_ESC)
#define KC_SFBSL   RSFT_T(KC_BSLS)
#define KC_SHINS   LSFT(KC_INS)
#define KC_FN      MO(_FN)

enum xd75_layers {
_QWERTY,
_COLEMAK,
_FN,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

[_QWERTY] = LAYOUT_ortho_5x15(
KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_MINS, KC_PSCR, KC_EQL, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC,
KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_LBRC, KC_INS, KC_RBRC, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_QUOT,
KC_CTESC, KC_A, KC_S, KC_D, KC_F, KC_G, KC_HOME, KC_DEL, KC_PGUP, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_ENT,
KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_END, KC_UP, KC_PGDN, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_SFBSL,
KC_LCTL, KC_LGUI, KC_LALT, KC_FN, KC_SPC, KC_SPC, KC_LEFT, KC_DOWN, KC_RIGHT, KC_SPC, KC_SPC, KC_FN, KC_RALT, KC_RGUI, KC_RCTL,
),
[_COLEMAK] = LAYOUT_ortho_5x15(
KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_MINS, KC_PSCR, KC_EQL, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC,
KC_TAB, KC_Q, KC_W, KC_F, KC_P, KC_B, KC_LBRC, KC_INS, KC_RBRC, KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_QUOT,
KC_CTESC, KC_A, KC_R, KC_S, KC_T, KC_G, KC_HOME, KC_DEL, KC_PGUP, KC_M, KC_N, KC_E, KC_I, KC_O, KC_ENT,
KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_D, KC_END, KC_UP, KC_PGDN, KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH, KC_SFBSL,
KC_LCTL, KC_LGUI, KC_LALT, KC_FN, KC_SPC, KC_SPC, KC_LEFT, KC_DOWN, KC_RIGHT, KC_SPC, KC_SPC, KC_FN, KC_RALT, KC_RGUI, KC_RCTL,
),
[_FN] = LAYOUT_ortho_5x15(
KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_NLCK, KC_SLSH, KC_ASTR, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12,
KC_MSEL, KC_CALC, KC_MYCM, KC_MAIL, RGB_HUD, RGB_HUI, KC_P7, KC_P8, KC_P9, KC_MINS, KC_TRANSPARENT, KC_TRANSPARENT, KC_PSCR, KC_SLCK, KC_PAUS,
KC_MPRV, KC_MPLY, KC_MNXT, KC_E, RGB_SAD, RGB_SAI, KC_P4, KC_P5, KC_P6, KC_PLUS, KC_TRANSPARENT, RESET, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
KC_VOLD, KC_MUTE, KC_VOLU, KC_APP, RGB_VAD, RGB_VAI, KC_P1, KC_P2, KC_P3, KC_PENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
KC_TRANSPARENT, KC_TRANSPARENT, RGB_TOG, KC_FN, RGB_RMOD, RGB_MOD, KC_P0, KC_TRANSPARENT, KC_PDOT, KC_PENT, KC_PENT, KC_FN, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT,
)
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode)    {

 case KC_COLEMAK:
 if (record->event.pressed) {
     set_single_persistent_default_layer(_COLEMAK);
 }
 return false;
 break;

 case KC_QWERTY:
 if (record->event.pressed) {
     set_single_persistent_default_layer(_QWERTY);
 }
 return false;
 break;

 }
 return true;
 }
